export const ROUTERS = {
  HOME: '/',
  LOGIN: '/login',
  PRODUCT_LIST: '/products',
  PROFILE: '/profile',
  PRODUCT_DETAIL: '/products/:id/:id_kieugiay',
  ADD_PRODUCT: '/addproduct',
  DETAIL_PRODUCT: '/detailproducts/:id',
  READ_PRODUCT: '/readproduct',
  EDIT_PRODUCT: '/editproduct/:id',
  ADD_SIZE: '/addsize',
  ADD_COLOR: '/addcolor',
  READ_SIZE: '/readsize',
  READ_COLOR: '/readcolor',
  READ_ORDER: '/readorder',
  READ_USER: '/readuser',
  READ_TYPE: '/readtype',
  ADD_TYPE: '/addtype',
  ORDER_DETAIL: '/readorder/orderdetai/:id',
  CHECKOUT_STEP_1: '/checkout/step1',
  CHECKOUT_STEP_2: '/checkout/step2',
  CHECKOUT_STEP_3: '/checkout/step3',
  ADMIN: '/admin',
  EDIT_PROFILE: '/profile/edit/',
  STATISTIC: '/statistic',
  ADD_SALE: '/addsale',
  READ_SALE: '/readsale',
  ADD_BANNER: '/addbanner',
  READ_BANNER: '/readbanner',
  FORGOT_PASSWORD: '/forgotpwd',
  RESET_PASSWORD: '/resetpwd/:id',
  NEWS: '/news',
  ADD_NEWS: '/addnews',
  READ_NEWS: '/readnews',
  EDIT_NEWS:'/readnews/editnews/:id',
  NEWS_DETAIL: '/news/:id'
}